### PR TITLE
Import Module issue (dataset, training)

### PR DESCRIPTION
**Pull request by vinamramunot-tech**

### CODE REVIEW

**Comment by vinamramunot-tech** [comment]
I will re-iterate why this change is being tested. The original commands from the [readme](https://github.com/BenAAndrew/Voice-Cloning-App/blob/main/dataset/dataset.md) were causing an issue. 

>> Running the program from root directory which is:
root


> Align
`python3 .\dataset\forced_alignment\align.py --audio_path .\dataset\forced_alignment\test.wav --script  .\dataset\forced_alignment\book.txt --aligned aligned.json`

> Generate clips
`python3 .\dataset\clip_generator.py --audio_path .\dataset\forced_alignment\test.wav --forced_alignment_path .\aligned.json --output_path wavs --label_path metadata.csv`

---
> Running programs images
https://github.com/BenAAndrew/Voice-Cloning-App/issues/5#issue-834137013
https://github.com/BenAAndrew/Voice-Cloning-App/issues/5#issuecomment-801469139

**Comment by BenAAndrew** [comment]
@vinamramunot-tech Thanks for the PR. I will test soon and if everything still works I'll merge

**Comment by vinamramunot-tech** [comment]
I also want to let you know that these changes suggested were because I was only trying via command line. I haven't tried the web app because it didn't accept my input for the dataset. Please let me know if you have any questions or concerns.

**Comment by BenAAndrew** [comment]
@vinamramunot-tech I've tried testing it with the app but it cannot find the imports now. I will look into fixing these imports for the CLI approach at a later stage but were probably going to need to do this differently

**Comment by vinamramunot-tech** [comment]
@BenAAndrew That works! I am going to place this in draft until we come back to this discussion at a later stage. For now, I will try out the web page again.

**Comment by BenAAndrew** [comment]
This has been fixed in https://github.com/BenAAndrew/Voice-Cloning-App/commit/92f3cebd85c43063d55b1b63cce6c0d64bd6c6c8

**Pull request closed without merging**
