### PR TITLE
webrtc py package name update

### PR DESCRIPTION
**Pull request by vinamramunot-tech**
I believe the webrtc module name has changes to webrtcvad-wheels. command to run it is `pip3 install webrtcvad-wheels`. I had to run this to make it work. I apologize for not sharing the error message. Please let me know if you are able to test it. It is alright if you are not able to test. It doesn't affect it much anyways, so we can leave it without updating it.

### CODE REVIEW

**Comment by BenAAndrew** [comment]
@vinamramunot-tech Good suggestion. I will add it to the list of things to test and if I'm happy everything still works I'll merge

**Comment by vinamramunot-tech** [comment]
I will keep this under draft until you complete testing. You can reopen this PR once you test it. It will be easier for you too.

**Comment by BenAAndrew** [comment]
@vinamramunot-tech Just tested and the alignment is still working. I'm just going to fix the version number and then merge

**Comment by BenAAndrew** [comment]
@vinamramunot-tech Unfortunately this update broke the pyinstaller executable so I've reverted it in https://github.com/BenAAndrew/Voice-Cloning-App/commit/b6c7151f3a878bfecbbc6d6805f78809436cd4e2

**Pull request merged**
